-- 코드를 입력하세요
/*SELECT 
 EXTRACT(YEAR FROM SALES_DATE) AS YEAR
,EXTRACT(MONTH FROM SALES_DATE) AS MONTH
,A.GENDER AS GENDER
,A.USER_ID AS USER_ID
FROM USER_INFO  A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE),EXTRACT(MONTH FROM SALES_DATE),GENDER,A.USER_ID
ORDER BY EXTRACT(YEAR FROM SALES_DATE) ASC,EXTRACT(MONTH FROM SALES_DATE) asc,GENDER ASC;*/

SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR
      ,EXTRACT(MONTH FROM SALES_DATE) AS MONTH
      ,GENDER
      ,COUNT(disTINCT A.USER_id) AS USERS
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
AND GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM SALES_DATE),EXTRACT(MONTH FROM SALES_DATE), GENDER
ORDER BY EXTRACT(YEAR FROM SALES_DATE) ASC,EXTRACT(MONTH FROM SALES_DATE) asc,GENDER ASC;